# Generated by Django 5.1.4 on 2024-12-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullName',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NOT STARTED', 'Not Started'), ('IN PROGRESS', 'IN Progress'), ('FINISHED', 'Finished'), ('HALTED', 'Halted'), ('CANCELLED', 'Cancelled')], default='NOT STARTED'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT STARTED', 'Not Started'), ('IN PROGRESS', 'IN Progress'), ('FINISHED', 'Finished'), ('HALTED', 'Halted'), ('CANCELLED', 'Cancelled')], default='NOT STARTED'),
        ),
    ]
