# Generated by Django 5.1.4 on 2024-12-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_user_fullname_alter_project_status_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
